name: flutter_selectable_themes_example
description: The example of selectable themes for Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  material_design_icons_flutter: 4.0.5045
  provider: ^4.0.5
  shared_preferences: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true